version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
      until php -r 'new PDO(\"mysql:host=db;dbname=stonkspizza\", \"root\", \"root\");'; do
        echo 'Waiting for database...';
        sleep 2;
      done &&
      php artisan migrate --force &&
      apache2-foreground
      "

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stonkspizza
    ports:
      - "3306:3306"
