name: Production Deployment

on:
  push:
    branches: ["main"]

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/stonkspizza:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/stonkspizza:${{ github.sha }}

      - name: Deploy to local production
        run: docker compose -f docker-compose.yaml -f docker-compose.override.production.yaml up -d

      - name: Show URL
        run: echo "Production running at http://localhost:8000"
