name: Staging Deployment

on:
  push:
    branches: ["staging"]

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run migrations
        run: docker exec $(docker ps -qf "name=stonkspizza_app_1") php artisan migrate --force

      - name: Check containers
        run: docker ps
