name: Staging Deployment

on:
  push:
    branches: ["staging"]

jobs:
  staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/stonkspizza:staging
            ${{ secrets.DOCKERHUB_USERNAME }}/stonkspizza:${{ github.sha }}

      - name: Setup .env for staging
        run: |
          cat <<EOF > .env
          APP_NAME=Stonkspizza
          APP_ENV=staging
          APP_KEY=${{ secrets.APP_KEY }}
          APP_DEBUG=true
          APP_URL=http://staging.example.com

          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=stonkspizza_staging
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          CACHE_DRIVER=file
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          EOF

      - name: Start Docker Compose (staging)
        run: docker compose up -d

      - name: Run migrations
        run: docker compose exec -T app php artisan migrate --force

      - name: Check containers
        run: docker ps
